---
version: "3.7"
services:
  ubuntu-vnc-xfce-g3:
    build: .
    image: ghcr.io/capsulecorplab/ltc-workspace-image:dev
    ports:
      - "5901:5901"
    user: "headless"
    environment:
      VNC_PW: password
    shm_size: '512m'
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - type: bind
        source: ./persistence-layer
        target: /home/headless
    security_opt:
      - seccomp=unconfined
...
